# Generated by Django 4.2.9 on 2024-03-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stockAvailable',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
