# Generated by Django 4.2.9 on 2024-03-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_product_stockavailable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stockAvailable',
            field=models.BooleanField(default=True),
        ),
    ]
