# Generated by Django 4.2.9 on 2024-03-24 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_order_orderitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='OrderItems',
            new_name='OrderItem',
        ),
    ]
