# Generated by Django 4.2.9 on 2024-04-05 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_rating_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='average_rating',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
